name: Bug report
description: Report a reproducible bug
labels: [bug]
body:
    - type: textarea
      id: summary
      attributes:
          label: Summary
          description: Clear and concise bug description
      validations:
          required: true
    - type: textarea
      id: steps
      attributes:
          label: Steps to reproduce
      validations:
          required: true
    - type: textarea
      id: expected
      attributes:
          label: Expected behavior
      validations:
          required: true
    - type: textarea
      id: actual
      attributes:
          label: Actual behavior
      validations:
          required: true
