name: Bug report
description: Report a reproducible bug in Flask Forge Template
labels: [bug]
body:
    - type: markdown
      attributes:
          value: |
              Thanks for helping improve Flask Forge Template.
              Repository: https://github.com/Ali-zeiynali/flask-forge-template
    - type: textarea
      id: summary
      attributes:
          label: Summary
          description: Clear and concise bug description
      validations:
          required: true
    - type: textarea
      id: steps
      attributes:
          label: Steps to reproduce
      validations:
          required: true
    - type: textarea
      id: expected
      attributes:
          label: Expected behavior
      validations:
          required: true
    - type: textarea
      id: actual
      attributes:
          label: Actual behavior
      validations:
          required: true
    - type: input
      id: contact
      attributes:
          label: Optional contact email
          description: If you want maintainers to follow up privately
      validations:
          required: false
