name: Feature request
description: Suggest an improvement for Flask Forge Template
labels: [enhancement]
body:
    - type: markdown
      attributes:
          value: |
              Before proposing a feature, check existing issues in:
              https://github.com/Ali-zeiynali/flask-forge-template/issues
    - type: textarea
      id: problem
      attributes:
          label: Problem statement
          description: What problem are you trying to solve?
      validations:
          required: true
    - type: textarea
      id: proposal
      attributes:
          label: Proposed solution
      validations:
          required: true
    - type: textarea
      id: alternatives
      attributes:
          label: Alternatives considered
      validations:
          required: false
